PRE_DEFINED_PARAMETER_WITH_VAR = ['TKOUT_TIME','TKIN_TIME','MARS_TIME_ROBOT','MARS_TIME_HW']
PRE_DEFINED_PARAMETER = ['EQP','CH','PPID','LOT_ID']

#PROBLEM_TYPE
REGRESSION = 'REGRESSION'
CLASSIFICATION = 'CLASSIFICATION'

#SPACE_MODEL_CODE
KERTAS = '1'
XGBOOST = '2'
LIGHTGBM = '3'
VIRTUAL_MODEL = '4'
VIRTUAL_MODEL = '5'
MULTI_LEVEL_REG = '6'
MULTI_LEVEL_LOGISTIC = '7'
LOGISTIC_REG = '8'
IN_WAFER = '9'
RIDGE ='10'
META_METI = '11'
IMAGE_AI_LOW_FRAME ='12'
IMAGE_AI_IMAGE_WARNING = '13'
META_METI_PROVISION = '14'
FDRY_ENSEMBLE = '15'
TORCH = '16'
MOONSHOT_IMAGE = '17'
IMAGE_IA_HVSEM = '18'
IMAGE_AI_PROVISION = '19'

# GPU 모델 실행 상태
GPU_MODEL_EXECUTOR_SUCCESS = 'SUCCESS'

MOONSHOT_IMAGE_FTP_PATH_FMT = ''
RUN_MODE_SERVER = 'SERVER'
RUN_MODE_INFERENCE = 'INFERENCE'
